# Generated by Django 4.0.4 on 2022-05-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='originaldata',
            name='溶解氧',
            field=models.CharField(default='', max_length=64),
        ),
    ]
