# Generated by Django 4.0.4 on 2022-05-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataModel', '0003_originaldata_bod_originaldata_cod_originaldata_高锰酸盐'),
    ]

    operations = [
        migrations.AddField(
            model_name='originaldata',
            name='总氮',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='总磷',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='氨氮',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='铜',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='锌',
            field=models.CharField(default='', max_length=64),
        ),
    ]
