# Generated by Django 4.0.4 on 2022-05-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataModel', '0004_originaldata_总氮_originaldata_总磷_originaldata_氨氮_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='originaldata',
            name='六价铬',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='挥发酚',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='氟化物',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='氰化物',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='汞',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='石油类',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='砷',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='硒',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='硫化物',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='粪大肠菌群',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='铅',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='镉',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='阴离子表面活性剂',
            field=models.CharField(default='', max_length=64),
        ),
    ]
