# Generated by Django 4.0.4 on 2022-05-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataModel', '0006_originaldata_水质类别_alter_originaldata_bod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationRulesWithData',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('antecedents', models.CharField(default='', max_length=256)),
                ('consequents', models.CharField(default='', max_length=256)),
                ('ant_support', models.CharField(default='', max_length=256)),
                ('con_support', models.CharField(default='', max_length=256)),
                ('support', models.CharField(default='', max_length=256)),
                ('confidence', models.CharField(default='', max_length=256)),
                ('lift', models.CharField(default='', max_length=256)),
                ('leverage', models.CharField(default='', max_length=256)),
                ('conviction', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AssociationRulesWithStandard',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('antecedents', models.CharField(default='', max_length=256)),
                ('consequents', models.CharField(default='', max_length=256)),
                ('ant_support', models.CharField(default='', max_length=256)),
                ('con_support', models.CharField(default='', max_length=256)),
                ('support', models.CharField(default='', max_length=256)),
                ('confidence', models.CharField(default='', max_length=256)),
                ('lift', models.CharField(default='', max_length=256)),
                ('leverage', models.CharField(default='', max_length=256)),
                ('conviction', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
