# Generated by Django 4.0.4 on 2022-05-05 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataModel', '0008_alter_associationruleswithdata_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationruleswithdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='associationruleswithstandard',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='originaldata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
