# Generated by Django 4.0.4 on 2022-05-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataModel', '0009_alter_associationruleswithdata_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('context', models.CharField(default='', max_length=1024)),
            ],
        ),
    ]
