# Generated by Django 4.0.4 on 2022-05-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataModel', '0010_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='originaldata',
            name='pH',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='所属城市',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='所属水系',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='断面名称',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='日期',
            field=models.CharField(default='0', max_length=64),
        ),
        migrations.AddField(
            model_name='originaldata',
            name='水温',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
