# Generated by Django 4.0.4 on 2022-05-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataModel', '0012_frequentitemsetswithdata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationruleswithdata',
            name='ant_support',
            field=models.FloatField(default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='associationruleswithdata',
            name='con_support',
            field=models.FloatField(default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='associationruleswithdata',
            name='confidence',
            field=models.FloatField(default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='associationruleswithdata',
            name='leverage',
            field=models.FloatField(default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='associationruleswithdata',
            name='lift',
            field=models.FloatField(default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='associationruleswithdata',
            name='support',
            field=models.FloatField(default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='associationruleswithstandard',
            name='ant_support',
            field=models.FloatField(default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='associationruleswithstandard',
            name='con_support',
            field=models.FloatField(default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='associationruleswithstandard',
            name='confidence',
            field=models.FloatField(default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='associationruleswithstandard',
            name='leverage',
            field=models.FloatField(default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='associationruleswithstandard',
            name='lift',
            field=models.FloatField(default=0, max_length=256),
        ),
        migrations.AlterField(
            model_name='associationruleswithstandard',
            name='support',
            field=models.FloatField(default=0, max_length=256),
        ),
    ]
